name: Deploy on server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy branch master
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Git repository and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/azureuser/finalApp
            git init
            git remote add origin https://github.com/karangarg218/FarAlpha.git
            git fetch origin
            git checkout master
            git pull origin master
            npm install
            /usr/local/bin/pm2 restart app.js
