name: Deploy on server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy branch master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and restart the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/azureuser/finalApp
            git checkout -- *
            git checkout master
            git pull origin master

            sudo env PATH=$PATH:/home/azureuser/.nvm/versions/node/v20.11.1/bin npx pm2 restart app.js
