name: Access server
on: push
jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: echo hello world > hello.txt
