name: Deploy on server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy branch master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and restart the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/azureuser/nodeapp
            git checkout -- *
            git checkout master
            git pull origin master
            sudo apt-get update

            # Check if Node.js is installed
            if ! command -v node &> /dev/null; then
              sudo apt-get install -y nodejs
            fi

            # Check if npm is installed
            if ! command -v npm &> /dev/null; then
              sudo apt-get install -y npm
            fi

            # Check if PM2 is installed
            if ! command -v pm2 &> /dev/null; then
              npm install pm2 -g
            fi

            npm install
            pm2 restart app.js
