name: Deploy on server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy branch master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and restart the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/azureuser/nodeapp
            git checkout -- *
            git checkout master
            git pull origin master
            npm install
            pm2 restart app.js
