name: Deploy and Start App on Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear known hosts file
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keygen -R ${{ secrets.AZURE_HOST }}

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Deploy code to Azure VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
          scp -o StrictHostKeyChecking=no -i ssh_key.pem -r ./src/* ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_HOST }}:~/src/
          rm ssh_key.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Node.js and pm2
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Start Node.js application with pm2
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_HOST }} "cd ~/src && pm2 start app.js --name app"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Notify on success
        if: success()
        run: echo "Deployment and startup of Node.js application on Azure VM successful. Notify stakeholders here."

      - name: Notify on failure
        if: failure()
        run: echo "Deployment and startup of Node.js application on Azure VM failed. Notify stakeholders here."
